import { execFile } from 'node:child_process';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { promisify } from 'node:util';

const pExecFile = promisify(execFile);

// 生成「启动」文件夹里的无窗口启动器。注释保持纯 ASCII：
// wscript 按 ANSI 读取 .vbs，中文注释在英文系统上会乱码（本仓库旧模板已踩过）。
export function renderVbs(ps1Path) {
  const escaped = ps1Path.replace(/"/g, '""');
  return [
    `' VaultSync hidden launcher (generated by: npm run setup)`,
    `' Starts start-vaultsync.ps1 without a console window.`,
    `Set sh = CreateObject("Wscript.Shell")`,
    `sh.Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -File ""${escaped}""", 0, False`,
    ``,
  ].join('\r\n');
}

// vaultPath 统一写成正斜杠：JSON 里反斜杠要转义，正斜杠免去用户手改时的坑
export function renderConfig(vaultPath) {
  const normalized = vaultPath.replace(/\\/g, '/').replace(/\/+$/, '');
  return JSON.stringify({ vaultPath: normalized, debounceSeconds: 30, pollMinutes: 5 }, null, 2) + '\n';
}

async function defaultListRemotes(vaultPath) {
  const { stdout } = await pExecFile('git', ['-C', vaultPath, 'remote'], {
    timeout: 15000,
    windowsHide: true,
    env: { ...process.env, GIT_TERMINAL_PROMPT: '0' },
  });
  return stdout.split(/\r?\n/).map((s) => s.trim()).filter(Boolean);
}

// 配置向导的 Vault 校验：每步失败都给出可执行的下一步，而不是一句 "invalid"
export async function validateVault(vaultPath, deps = {}) {
  const exists = deps.exists ?? existsSync;
  const listRemotes = deps.listRemotes ?? defaultListRemotes;
  if (!vaultPath || !exists(vaultPath)) {
    throw new Error(`目录不存在: ${vaultPath}`);
  }
  if (!exists(path.join(vaultPath, '.git'))) {
    throw new Error(
      `该目录不是 git 仓库: ${vaultPath}\n  请先在 Vault 目录初始化并关联 GitHub 仓库:\n  git init && git remote add origin <仓库地址>`
    );
  }
  const remotes = await listRemotes(vaultPath);
  if (remotes.length === 0) {
    throw new Error(
      `该仓库还没有 remote，vaultsync 需要推送到 GitHub:\n  git -C "${vaultPath}" remote add origin <仓库地址>`
    );
  }
  return true;
}

export function startupVbsPath(env = process.env) {
  if (!env.APPDATA) {
    throw new Error('找不到 APPDATA 环境变量，无法定位「启动」文件夹');
  }
  return path.join(env.APPDATA, 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup', 'start-vaultsync.vbs');
}
